// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SDMS_API.Data;

namespace SDMS_API.Migrations
{
    [DbContext(typeof(SDMSDbContext))]
    [Migration("20200921154938_AddedWarehouseTableAgainWithDbSet")]
    partial class AddedWarehouseTableAgainWithDbSet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SDMS_API.Data.ChartofAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDebit")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDetailAccount")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ParentAccountId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentAccountId");

                    b.ToTable("ChartofAccounts");
                });

            modelBuilder.Entity("SDMS_API.Data.MeasureUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("MeasureUnits");
                });

            modelBuilder.Entity("SDMS_API.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("ActualPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("CostOfGoodsSoldCOAId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InventoryCOAId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MeasureUnitID")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("RetailPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SaleCOAId")
                        .HasColumnType("int");

                    b.Property<int?>("SaleDiscountCOAId")
                        .HasColumnType("int");

                    b.Property<int?>("SaleReturnCOAId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CostOfGoodsSoldCOAId");

                    b.HasIndex("InventoryCOAId");

                    b.HasIndex("MeasureUnitID");

                    b.HasIndex("SaleCOAId");

                    b.HasIndex("SaleDiscountCOAId");

                    b.HasIndex("SaleReturnCOAId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SDMS_API.Data.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("SDMS_API.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SDMS_API.Data.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("SDMS_API.Data.ChartofAccount", b =>
                {
                    b.HasOne("SDMS_API.Data.ChartofAccount", "TblParentChartOfAccount")
                        .WithMany("TblChildChartOfAccounts")
                        .HasForeignKey("ParentAccountId");
                });

            modelBuilder.Entity("SDMS_API.Data.Product", b =>
                {
                    b.HasOne("SDMS_API.Data.ProductCategory", "TblProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SDMS_API.Data.ChartofAccount", "TblCostOfGoodsSoldChartOfAccount")
                        .WithMany("TblCostOfGoodsSoldProducts")
                        .HasForeignKey("CostOfGoodsSoldCOAId");

                    b.HasOne("SDMS_API.Data.ChartofAccount", "TblInventoryChartOfAccount")
                        .WithMany("TblInventoryProducts")
                        .HasForeignKey("InventoryCOAId");

                    b.HasOne("SDMS_API.Data.MeasureUnit", "TblMeasureUnit")
                        .WithMany("Products")
                        .HasForeignKey("MeasureUnitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SDMS_API.Data.ChartofAccount", "TblSaleChartOfAccount")
                        .WithMany("TblSaleProducts")
                        .HasForeignKey("SaleCOAId");

                    b.HasOne("SDMS_API.Data.ChartofAccount", "TblSaleDiscountChartOfAccount")
                        .WithMany("TblSaleDiscountProducts")
                        .HasForeignKey("SaleDiscountCOAId");

                    b.HasOne("SDMS_API.Data.ChartofAccount", "TblSaleReturnChartOfAccount")
                        .WithMany("TblSaleReturnProducts")
                        .HasForeignKey("SaleReturnCOAId");
                });
#pragma warning restore 612, 618
        }
    }
}
